# Generated by Django 4.0.2 on 2022-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
                ('alias', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('structure_value', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ad_group_id', models.IntegerField()),
                ('campaign_id', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('conversion_value', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('search_term', models.CharField(max_length=255)),
            ],
        ),
    ]
