# Generated by Django 4.0.2 on 2022-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='ad_group_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='adgroup',
            name='campaign_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='ad_group_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='campaign_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='clicks',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='conversion_value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='conversions',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='cost',
            field=models.BigIntegerField(),
        ),
    ]
